"""Bitwise CPU equivalence of the extracted reference and archived implementation.

Run from the repository root with:
    python -m unittest discover -s tests -p 'test_taxosieve_reference.py' -v

Each implementation runs in a fresh interpreter, using the same small archived
fixtures. No user images or pretrained weights are opened, and all checkpoint
snapshots are temporary. Set TAXOSIEVE_ORIGINAL_SOURCE (or H02_ORIGINAL_SOURCE)
to an external, intact reviewed source snapshot to enable the optional archived
comparison. Both workers read the current dataset's identical taxonomy input.
"""
import argparse
from contextlib import ExitStack, redirect_stdout
import copy
import importlib.util
import inspect
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import types
import unittest
from unittest.mock import patch
import warnings


ROOT = Path(__file__).resolve().parents[1]


def _load_test_snapshot(path):
    """Load only trusted temporary snapshots generated by our own workers."""
    import torch
    options = {"map_location": "cpu"}
    if "weights_only" in inspect.signature(torch.load).parameters:
        options["weights_only"] = False
    return torch.load(path, **options)


def _snapshot_worker(args):
    # The intentionally tiny TEST fixture includes a singleton class. Its
    # confusion matrix warning does not concern the production taxonomy.
    warnings.filterwarnings("ignore", message="A single label was found in", category=UserWarning)
    sys.path.insert(0, str(args.repo))
    import torch
    import numpy as np
    torch.set_num_threads(1)
    from taxosafe_support import pipeline, protocol
    from taxosafe_support.evidence import HierarchicalEvidence
    from taxosafe_support.episodes import build_episodes
    from taxosafe_support.losses import reference_pair_losses


    def module_file(name, path):
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    core = module_file('core_fixtures', args.original / 'tests/test_taxosafe_support_core.py')
    fixtures = module_file('pipeline_fixtures', args.original / 'tests/test_taxosafe_support_pipeline.py')


    def cloned(value):
        if torch.is_tensor(value):
            return value.detach().cpu().clone()
        if isinstance(value, dict):
            return {k: cloned(v) for k, v in value.items()}
        if isinstance(value, (list, tuple)):
            return type(value)(cloned(v) for v in value)
        return value


    snapshot = {}
    for name in ('encoders.py', 'episodes.py', 'reference.py', 'support.py', 'preprocessing.py', 'membership_calibration.py'):
        assert (args.repo/'taxosafe_support'/name).read_bytes() == (args.original/'taxosafe_support'/name).read_bytes()
    snapshot['unchanged_reference_math_files'] = True
    raw_config = args.original/'configs/Zooplankton_Taxonomic_Tree/TaxoSafe_support_reference.yml'
    cfg = protocol.effective_config(raw_config, 'main', 1)
    snapshot['effective_config'] = cfg
    snapshot['object_hash'] = protocol.object_hash(cfg)

    for locals_enabled in (True, False):
        for excluded in (False, True):
            bank, encoded = core.fixture(locals=locals_enabled)
            torch.manual_seed(137)
            model = HierarchicalEvidence(8, core.MAPPING, decoupled=True, membership_mode='reference')
            label = str((locals_enabled, excluded))
            result = {'initial_state': cloned(model.state_dict()), 'rng_after_init': torch.get_rng_state().clone()}
            with torch.no_grad():
                for head in (model.parent_reference, model.fine_reference):
                    head.residual[-1].weight.fill_(.04)
            labels = torch.arange(5)
            queries = list(bank.hashes)[::3] if excluded else None
            episodes = build_episodes(labels, core.MAPPING, seed=59)
            pairs = model.reference_pairs(encoded, bank)
            result['outputs'] = {key: cloned(model(encoded, bank, mask, query_hashes=queries,
                                      reference_pair_logits=pairs)) for key, mask in episodes['masks'].items()}
            empty = model(encoded, bank, torch.zeros(5, 5, dtype=torch.bool))
            empty_loss = -empty['log_probs'][:, 0].mean() + sum(reference_pair_losses(empty, labels, core.MAPPING).values())
            empty_loss.backward()
            result['empty'] = cloned(empty)
            result['empty_grads'] = {key: cloned(v.grad) if v is not None else None for key,v in encoded.items()}
            assert all(v is None or bool(torch.isfinite(v).all()) for v in result['empty_grads'].values())
            snapshot['evidence_'+label] = result

    for episode_weight in (0., .4, 1.):
        bank, encoded = core.fixture()
        gen = torch.Generator().manual_seed(75)
        encoded['leaf_logits'] = torch.randn(5, 5, generator=gen, requires_grad=True)
        encoded['parent_logits'] = torch.randn(5, 3, generator=gen, requires_grad=True)
        anchor = torch.randn(5,5,generator=gen)
        torch.manual_seed(237)
        model = HierarchicalEvidence(8, core.MAPPING, decoupled=True, membership_mode='reference')
        with torch.no_grad():
            for head in (model.parent_reference, model.fine_reference):
                head.residual[-1].weight.fill_(.04)
        loss, terms, counts = pipeline.training_loss(encoded, torch.arange(5), torch.arange(5),
            list(bank.hashes)[::3], bank, model, cfg, {'leaf_to_parent': core.MAPPING},
            seed=19, episode_weight=episode_weight, anchor=anchor)
        loss.backward()
        result = {'loss': cloned(loss), 'terms': cloned(terms), 'counts': counts,
                  'model_gradients': {name: cloned(p.grad) for name,p in model.named_parameters()},
                  'query_gradients': {name: cloned(v.grad) for name,v in encoded.items()}}
        assert bool(torch.isfinite(loss))
        assert all(v is None or bool(torch.isfinite(v).all()) for v in result['model_gradients'].values())
        snapshot['training_loss_'+str(episode_weight)] = result

    # Exercise actual reference train/calibrate/test stage functions with a tiny
    # deterministic encoder and vectors, never with user images or pretrained CLIP.
    tiny_cfg, groups = fixtures.fixture()
    tiny_cfg['support'].update(decoupled=True, membership='reference', reference_topk=2,
                               local_enabled=True, shared_encoder=False, parent_holdout_enabled=True)
    tiny_cfg['calibration'] = dict(decoder='membership', policy='known_first',
                                  threshold_grid='quantile', membership_grid_points=7, source_loo=True)
    tiny_cfg['evaluation_gates'] = copy.deepcopy(cfg['evaluation_gates'])


    def load_stage(config, stage, meta, forbidden_hashes=(), forbidden_sources=()):
        selected = {key: copy.deepcopy(groups[key]) for key in protocol.STAGE_SPLITS[stage]}
        audit = protocol.audit_rows(selected, forbidden_hashes, forbidden_sources, allow_within_split=stage=='test')
        for key in audit:
            audit[key]['manifest_sha256'] = 'fixture_'+key
        return selected, audit

    with tempfile.TemporaryDirectory() as temporary, ExitStack() as stack:
        directory = Path(temporary)/'run'
        for name, value in [('hierarchy', fixtures.META), ('signature', fixtures.SIGNATURE)]:
            stack.enter_context(patch.object(pipeline,name,return_value=value))
        stack.enter_context(patch.object(pipeline,'make_loader',side_effect=fixtures.loader))
        stack.enter_context(patch.object(pipeline,'make_backbone',side_effect=lambda *a: fixtures.TinyBackbone()))
        stack.enter_context(patch.object(pipeline,'load_stage_rows',side_effect=load_stage))
        stack.enter_context(redirect_stdout(io.StringIO()))
        pipeline.train(tiny_cfg, directory, torch.device('cpu'))
        pipeline.calibrate_run(tiny_cfg, directory, torch.device('cpu'))
        pipeline.test_run(tiny_cfg, directory, torch.device('cpu'))
        snapshot['tiny_best'] = pipeline._load_torch(directory/'training/best.pth')
        bank = pipeline._load_torch(directory/'training/support.pth')
        snapshot['tiny_bank'] = bank['bank']
        snapshot['tiny_router'] = json.loads((directory/'calibration/router.json').read_text())
        snapshot['tiny_test_metrics'] = json.loads((directory/'test/metrics.json').read_text())
        snapshot['tiny_test_predictions'] = (directory/'test/predictions.jsonl').read_text()

    # Real current taxonomy loading, with display-only termcolor shim in the old
    # source solely because it is absent in this executor's Python installation.
    if args.repo == args.original:
        term = types.ModuleType('termcolor')
        term.colored = lambda value,*a,**k: str(value)
        sys.modules.setdefault('termcolor',term)
    from loader.hierdata import _load_hierarchy
    taxonomy_path = args.taxonomy
    if not taxonomy_path.exists():
        raise FileNotFoundError('The current reference taxonomy is required: ' + str(taxonomy_path))
    hierarchy=_load_hierarchy({'hierarchy':str(taxonomy_path)})
    snapshot['taxonomy']={key:cloned(value) for key,value in hierarchy.items()}
    from models.clip import tokenize
    snapshot['tokenizer'] = tokenize(['a microscopy image of a Oithona plumifera.', 'a photo of a Calanus sinicus.'])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(snapshot, args.output)
    print('PASS snapshot', args.repo.name, 'items', len(snapshot), 'CUDA', torch.cuda.is_available())


class ReferenceEquivalenceTest(unittest.TestCase):
    def test_snapshot_loading_supports_old_and_new_torch_signatures(self):
        import torch

        path = Path("trusted_worker_snapshot.pt")
        snapshot = {"fixture": "temporary worker output"}
        calls = []

        def legacy_load(filename, map_location=None, **pickle_load_args):
            # Torch 1.12 forwards unknown kwargs to pickle, which rejects
            # weights_only. It must be omitted for this older signature.
            self.assertEqual(pickle_load_args, {})
            calls.append((filename, map_location))
            return snapshot

        def modern_load(filename, map_location=None, *, weights_only=None):
            self.assertIs(weights_only, False)
            calls.append((filename, map_location))
            return snapshot

        for loader in (legacy_load, modern_load):
            with self.subTest(loader=loader.__name__), patch.object(torch, "load", new=loader):
                self.assertIs(_load_test_snapshot(path), snapshot)
        self.assertEqual(calls, [(path, "cpu"), (path, "cpu")])

    def test_reference_matches_archived_execution_bitwise(self):
        import numpy as np
        import torch

        source = os.environ.get("TAXOSIEVE_ORIGINAL_SOURCE") or os.environ.get("H02_ORIGINAL_SOURCE")
        if not source:
            self.skipTest("Set TAXOSIEVE_ORIGINAL_SOURCE to an external reviewed snapshot for exact comparison")
        original = Path(source).expanduser().resolve()
        self.assertTrue((original / "tests" / "test_taxosafe_support_core.py").is_file(),
                        "An intact archived reference and its fixtures are required")
        counts = {"tensors": 0, "arrays": 0, "scalars": 0}

        def compare(expected, actual, path="snapshot"):
            if torch.is_tensor(expected):
                self.assertTrue(torch.is_tensor(actual), path)
                self.assertEqual(expected.dtype, actual.dtype, path)
                self.assertEqual(expected.shape, actual.shape, path)
                self.assertTrue(torch.equal(expected, actual), path)
                counts["tensors"] += 1
            elif isinstance(expected, np.ndarray):
                self.assertIsInstance(actual, np.ndarray, path)
                self.assertEqual(expected.dtype, actual.dtype, path)
                self.assertTrue(np.array_equal(expected, actual), path)
                counts["arrays"] += 1
            elif isinstance(expected, dict):
                self.assertIsInstance(actual, dict, path)
                self.assertEqual(list(expected), list(actual), path + " keys/order")
                for key in expected:
                    compare(expected[key], actual[key], path + "." + str(key))
            elif isinstance(expected, (list, tuple)):
                self.assertIs(type(expected), type(actual), path)
                self.assertEqual(len(expected), len(actual), path)
                for i, (left, right) in enumerate(zip(expected, actual)):
                    compare(left, right, path + "[" + str(i) + "]")
            else:
                self.assertEqual(expected, actual, path)
                counts["scalars"] += 1

        with tempfile.TemporaryDirectory(prefix="taxosieve_reference_equivalence_") as temporary:
            snapshots = []
            for name, repo in (("archived", original), ("current", ROOT)):
                output = Path(temporary) / (name + ".pt")
                process = subprocess.run([
                    sys.executable, str(Path(__file__).resolve()), "--worker",
                    "--repo", str(repo), "--original", str(original),
                    "--output", str(output), "--taxonomy", str(ROOT / "prepro/data/tree.npy")],
                    cwd=str(repo), capture_output=True,
                    text=True, timeout=60)
                self.assertEqual(process.returncode, 0,
                    name + " worker failed:\n" + process.stdout + process.stderr)
                snapshots.append(_load_test_snapshot(output))
            self.assertEqual(len(snapshots[0]), 17)
            compare(snapshots[0], snapshots[1])
        # Every scalar is already compared exactly above, including dict keys.
        # PyTorch checkpoint/optimizer metadata can add matching scalar fields
        # across supported runtime versions; that is not a math mismatch.
        self.assertEqual(counts["tensors"], 642)
        self.assertEqual(counts["arrays"], 1)
        self.assertGreaterEqual(counts["scalars"], 1322)


if __name__ == "__main__":
    if "--worker" in sys.argv:
        parser = argparse.ArgumentParser(description="Isolated reference equivalence snapshot worker")
        parser.add_argument("--worker", action="store_true")
        parser.add_argument("--repo", type=Path, required=True)
        parser.add_argument("--original", type=Path, required=True)
        parser.add_argument("--output", type=Path, required=True)
        parser.add_argument("--taxonomy", type=Path, required=True)
        _snapshot_worker(parser.parse_args())
    else:
        unittest.main()
